apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trussium-system

resources:
  - namespace.yaml
  - service-account.yaml
  - config-map.yaml
  - deployment.yaml
  - service.yaml
