apiVersion: v1
kind: ServiceAccount
metadata:
  name: trussium
  labels:
    app.kubernetes.io/name: trussium
    app.kubernetes.io/instance: trussium
    app.kubernetes.io/component: runtime
automountServiceAccountToken: false
imagePullSecrets:
  - name: ghcr-credentials
