apiVersion: v1
kind: Service
metadata:
  name: trussium
  labels:
    app.kubernetes.io/name: trussium
    app.kubernetes.io/instance: trussium
    app.kubernetes.io/component: runtime
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trussium
    app.kubernetes.io/instance: trussium
  ports:
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP
