apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trussium-system

resources:
  - ../../base
  - horizontal-pod-autoscaler.yaml
  - pod-disruption-budget.yaml

patches:
  - path: deployment-patch.yaml

images:
  - name: ghcr.io/trussiumhq/trussium
    newName: ghcr.io/trussiumhq/trussium
    newTag: "0.42.0"
